---
- hosts: all
  roles:
    - ubuntu-common

- hosts: vagrant
  roles: 
    - virtualenv-vagrant
    - dbserver
    - webserver

- hosts: production
  roles:
    - virtualenv-production
    - dbserver
    - webserver
